sudo: required
servieces:
  - docker

before_install:
  - docker build -t ernesto/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true ernesto/docker-react ernesto/docker-react npm run test