sudo: required
servieces:
  - docker

before_install:
  - docker build -t ernesto/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true ernesto/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-997739507955"
  bucke_path: "docker-react"
  on:
    branch: master
    access_key_id: secure: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"